### ISSUE TITLE
멀티 DB 지원 예제 구현

### ISSUE THREAD

**Issue by perhapsspy** [DanbiEduCorp/server_base#2]
1. 쓰기 - 마스터 / 읽기 - 슬레이브 
2. 앱별로 다른 DB에 접근

**Comment by perhapsspy** [comment]
읽기와 쓰기 DB는 이미 같은걸로 하고 있습니다.
모델 마미를 써서 실제로 DB에 값을 쓰지 않고 넘어가다보니 이런 이슈가 생기는거 같습니다. 라우터 자체는 잘 돌아갑니다. danbi_server에서 테스트는 실제로 데이터베이스를 사용하고 모델마미를 안쓰니 별 문제 없을거 같습니다.

**Comment by gulby** [comment]
넵. 코드를 참고하여 제쪽에 적용하여 테스트해 보겠습니다.
혹시라도 동일한 문제가 발생하게 되면 문의 드리겠습니다.
