### ISSUE TITLE
settings.CACHES 의 LOCATION 항목 관련 확인

### ISSUE THREAD

**Issue by gulby** [DanbiEduCorp/server_base#5]
0. Redis Backend 기준

1. 장고 매뉴얼을 보니 LOCATION 에 1개가 아닌 여러개(list)가 지정 가능하다 되어 있음

2. LOCATION 에 여러개를 지정한 경우, 샤딩 로직이 정확히 어떻게 되는지 파악 요청

3. 관련 샘플 제작

**Comment by perhapsspy** [comment]
# django 기본 backend
Django 문서에 나온 여러 location 설정이 가능한 캐시 백앤드는 memcached 뿐입니다.
memcached의 기능이고 알아서 작동합니다. 샤딩 기준은 딱히 없는걸로 보입니다.

# redis backend
별도의 확장 라이브러리를 설치해야 작동합니다. 많이 쓰이는 라이브러리가 두개 정도 있습니다.
둘 다 location 설정시 첫번째꺼는 마스터로 작동하고 두번째 이후로는 슬레이브로 동작이 고정되어 있습니다.

1. [django-redis](https://niwinz.github.io/django-redis/latest/)
    * 마스터-슬레이브 location 설정은 실험적이라고 언급되어 있습니다.
2. [django-redis-cache](http://django-redis-cache.readthedocs.io/en/latest/)

**Comment by gulby** [comment]
캐시 샤딩은 자체적으로 구현하는 방향으로 진행하겠습니다.
