### ISSUE TITLE
장고 로깅 샘플 구현 및 Sentry 연동

### ISSUE THREAD

**Issue by gulby** [DanbiEduCorp/server_base#6]
장고 로깅 샘플 구현 및 Sentry 연동 작업 부탁드립니다.

**Comment by perhapsspy** [comment]
Sentry는 danbi_server에 붙이는게 좋을거 같습니다. https://sentry.io/welcome/ 여기 가입하시고 초대주시면 진행하겠습니다.

**Comment by perhapsspy** [comment]
별도로 이야기 한 내용대로 server_base에 진행하고 sentry용으로 기본 에러와 커스텀 에러만 써서 gulby@maukistudio.com 계정으로 연결해두겠습니다.

**Comment by perhapsspy** [comment]
배포 하고 되는거 확인했습니다.  /500/sentry/ 라는 주소를 하나 만들어서 임의로 에러를 보고 하게 해놨습니다.

**Comment by gulby** [comment]
차주 목요일 (2월 23일) 에 제가 직접 적용해보고 완료 처리하겠습니다. 수고하셨습니다~

**Comment by gulby** [comment]
아직 적용은 못했지만, 추후 적용하면서 잘 안되면 온라인 지원 요청 드리겠습니다 ^^
